### ISSUE TITLE
ImportError: No module named django.contrib

### ISSUE THREAD

**Issue by hktalent** [Rev3rseSecurity/WebMap#15]
```
py2 admin.py
Traceback (most recent call last):
  File "admin.py", line 1, in <module>
    from django.contrib import admin
ImportError: No module named django.contrib


pip install django
Collecting django
  Downloading https://files.pythonhosted.org/packages/44/e7/872bbf76aa16b7a061698d75325dac023285db33db4bda8ba8fe5d3bb356/Django-1.11.16-py2.py3-none-any.whl (7.0MB)
    100% |████████████████████████████████| 7.0MB 3.5MB/s
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from django) (2018.7)
Installing collected packages: django
Successfully installed django-1.11.16


```

**Comment by hktalent** [comment]
in my kali linux
```
apt-get update && apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages \
    python3 python3-pip curl wget git wkhtmltopdf libssl1.0-dev
mkdir /opt/xml && mkdir /opt/notes && \
    wget -P /opt/ https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz && \
    cd /opt/ && tar -xvf /opt/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz

pip3 install Django requests xmltodict && \
    cd /opt/ && django-admin startproject nmapdashboard && cd /opt/nmapdashboard && \
    git clone https://github.com/Rev3rseSecurity/WebMap.git && \
    mv WebMap nmapreport && cd nmapreport && git checkout v2/master

cd /mytools/WebMap/docker
ln -s `pwd`/settings.py /opt/nmapdashboard/nmapdashboard/settings.py
ln -s `pwd`/urls.py /opt/nmapdashboard/nmapdashboard/urls.py

pip3 install Django requests xmltodict
ln -s `pwd` /opt/nmapdashboard/WebMap

cd /opt/nmapdashboard/
ln -s WebMap nmapreport

cd /opt/nmapdashboard && python3 manage.py migrate

python3 /opt/nmapdashboard/manage.py runserver 0:8000

firefox http://127.0.0.1:8000
```
so, is ok,thanks

**Comment by hktalent** [comment]
```
[05/Nov/2018 06:36:10] "GET /favicon.ico HTTP/1.1" 301 0
Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nmapdashboard/nmapreport/views.py", line 27, in details
    oo = xmltodict.parse(open('/opt/xml/'+request.session['scanfile'], 'r').read())
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'scanfile'
[05/Nov/2018 06:36:10] "GET /favicon.ico/ HTTP/1.1" 500 65921
Internal Server Error: /favicon.ico/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/nmapdashboard/nmapreport/views.py", line 27, in details
    oo = xmltodict.parse(open('/opt/xml/'+request.session['scanfile'], 'r').read())
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/sessions/backends/base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'scanfile'
[05/Nov/2018 06:36:10] "GET /favicon.ico/ HTTP/1.1" 500 65136
```
